{% set version = "0.2.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-badger
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/badger_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/badger/badger_{{ version }}.tar.gz
  sha256: e04cb8b531806c548807ed6d57b22f2eed31c5e25871c83f78262c1b46735ef8

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-desc
    - r-dlstats
    - r-rvcheck
    - r-usethis >=2.0.0
  run:
    - r-base
    - r-desc
    - r-dlstats
    - r-rvcheck
    - r-usethis >=2.0.0

test:
  commands:
    - $R -e "library('badger')"           # [not win]
    - "\"%R%\" -e \"library('badger')\""  # [win]

about:
  home: https://github.com/GuangchuangYu/badger
  license: Artistic-2.0
  summary: Query information and generate badge for using in README and GitHub Pages.
  license_family: OTHER
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0

extra:
  recipe-maintainers:
    - conda-forge/r
