{% set version = "0.2.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-badger
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/badger_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/badger/badger_{{ version }}.tar.gz
  sha256: 24d35c81f8780da5106b9aa083abf4cb982a3458247345daa646a08a0f18a19f

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-desc
    - r-dlstats
    - r-rvcheck
    - r-usethis >=2.0.0
  run:
    - r-base
    - r-desc
    - r-dlstats
    - r-rvcheck
    - r-usethis >=2.0.0

test:
  commands:
    - $R -e "library('badger')"           # [not win]
    - "\"%R%\" -e \"library('badger')\""  # [win]

about:
  home: https://github.com/GuangchuangYu/badger
  license: Artistic-2.0
  summary: Query information and generate badge for using in README and GitHub Pages.
  license_family: OTHER
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0

extra:
  recipe-maintainers:
    - conda-forge/r
